name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Change to your desired Node.js version

      # Step 3: Install dependencies and build the app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # The directory containing your static files
          # Optional: Specify the branch to deploy to (defaults to 'gh-pages')
          publish_branch: gh-pages  # Change if you're deploying to a different branch